<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace yiix\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "auth_assignment".
 *
 * @property string $item_name
 * @property string $user_id
 * @property integer $created_at
 *
 * @property \common\models\AuthItem $itemName
 * @property string $aliasModel
 */
abstract class AuthAssignment extends \melkov\db\ActiveRecord 
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%auth_assignment}}';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'updatedAtAttribute' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['item_name', 'user_id'], 'trim', 'skipOnEmpty' => true],
            [['item_name', 'user_id'], 'required'],
            [['item_name', 'user_id'], 'string', 'max' => 64],
            [['item_name'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\AuthItem::className(), 'targetAttribute' => ['item_name' => 'name']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'item_name' => Yii::t('label', 'Item Name'),
            'user_id' => Yii::t('label', 'User ID'),
            'created_at' => Yii::t('label', 'Created At'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getItemName()
    {
        return $this->hasOne(\common\models\AuthItem::className(), ['name' => 'item_name']);
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\AuthAssignmentQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\AuthAssignmentQuery(get_called_class());
    }


}
