<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace yiix\models\base;

use Yii;

/**
 * This is the base-model class for table "document_group_name".
 *
 * @property integer $id
 * @property string $name
 * @property integer $private_mem_group
 * @property integer $private_web_group
 *
 * @property \common\models\DocumentGroup[] $documentGroups
 * @property string $aliasModel
 */
abstract class DocumentGroupName extends \melkov\db\ActiveRecord 
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%document_group_name}}';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'trim', 'skipOnEmpty' => true],
            [['name'], 'required'],
            [['private_mem_group', 'private_web_group'], 'integer'],
            [['name'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('label', 'ID'),
            'name' => Yii::t('label', 'Name'),
            'private_mem_group' => Yii::t('label', 'Private Mem Group'),
            'private_web_group' => Yii::t('label', 'Private Web Group'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDocumentGroups()
    {
        return $this->hasMany(\common\models\DocumentGroup::className(), ['document_group_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\DocumentGroupNameQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\DocumentGroupNameQuery(get_called_class());
    }


}
