<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace yiix\models\base;

use Yii;

/**
 * This is the base-model class for table "document_group".
 *
 * @property integer $id
 * @property integer $document_group_id
 * @property integer $document_id
 *
 * @property \common\models\SiteContent $document
 * @property \common\models\DocumentGroupName $documentGroup
 * @property string $aliasModel
 */
abstract class DocumentGroup extends \melkov\db\ActiveRecord 
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%document_group}}';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['document_group_id', 'document_id'], 'required'],
            [['document_group_id', 'document_id'], 'integer'],
            [['document_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\SiteContent::className(), 'targetAttribute' => ['document_id' => 'id']],
            [['document_group_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\DocumentGroupName::className(), 'targetAttribute' => ['document_group_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('label', 'ID'),
            'document_group_id' => Yii::t('label', 'Document Group ID'),
            'document_id' => Yii::t('label', 'Document ID'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDocument()
    {
        return $this->hasOne(\common\models\SiteContent::className(), ['id' => 'document_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDocumentGroup()
    {
        return $this->hasOne(\common\models\DocumentGroupName::className(), ['id' => 'document_group_id']);
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\DocumentGroupQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\DocumentGroupQuery(get_called_class());
    }


}
