<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace yiix\models\base;

use Yii;

/**
 * This is the base-model class for table "migration".
 *
 * @property string $version
 * @property integer $apply_time
 * @property string $aliasModel
 */
abstract class Migration extends \melkov\db\ActiveRecord 
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%migration}}';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['version'], 'trim', 'skipOnEmpty' => true],
            [['version'], 'required'],
            [['apply_time'], 'integer'],
            [['version'], 'string', 'max' => 180]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'version' => Yii::t('label', 'Version'),
            'apply_time' => Yii::t('label', 'Apply Time'),
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\MigrationQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\MigrationQuery(get_called_class());
    }


}
