<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace yiix\models\base;

use Yii;

/**
 * This is the base-model class for table "site_template_var_type".
 *
 * @property integer $id
 * @property string $name
 *
 * @property \common\models\SiteTemplateVar[] $siteTemplateVars
 * @property string $aliasModel
 */
abstract class SiteTemplateVarType extends \melkov\db\ActiveRecord 
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%site_template_var_type}}';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'trim', 'skipOnEmpty' => true],
            [['name'], 'required'],
            [['name'], 'string', 'max' => 50],
            [['name'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('label', 'ID'),
            'name' => Yii::t('label', 'Name'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSiteTemplateVars()
    {
        return $this->hasMany(\common\models\SiteTemplateVar::className(), ['type_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\SiteTemplateVarTypeQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\SiteTemplateVarTypeQuery(get_called_class());
    }


}
