<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace yiix\models\base;

use Yii;

/**
 * This is the base-model class for table "site_keyword".
 *
 * @property integer $id
 * @property string $keyword
 *
 * @property \common\models\KeywordXref[] $keywordXrefs
 * @property \common\models\SiteContent[] $contents
 * @property string $aliasModel
 */
abstract class SiteKeyword extends \melkov\db\ActiveRecord 
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%site_keyword}}';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['keyword'], 'trim', 'skipOnEmpty' => true],
            [['keyword'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('label', 'ID'),
            'keyword' => Yii::t('label', 'Keyword'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getKeywordXrefs()
    {
        return $this->hasMany(\common\models\KeywordXref::className(), ['keyword_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getContents()
    {
        return $this->hasMany(\common\models\SiteContent::className(), ['id' => 'content_id'])->viaTable('yiix_keyword_xref', ['keyword_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\SiteKeywordQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\SiteKeywordQuery(get_called_class());
    }


}
