<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace yiix\models\base;

use Yii;

/**
 * This is the base-model class for table "site_content_meta_tag".
 *
 * @property integer $content_id
 * @property integer $meta_tag_id
 *
 * @property \common\models\SiteContent $content
 * @property \common\models\SiteMetaTag $metaTag
 * @property string $aliasModel
 */
abstract class SiteContentMetaTag extends \melkov\db\ActiveRecord 
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%site_content_meta_tag}}';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['content_id', 'meta_tag_id'], 'required'],
            [['content_id', 'meta_tag_id'], 'integer'],
            [['content_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\SiteContent::className(), 'targetAttribute' => ['content_id' => 'id']],
            [['meta_tag_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\SiteMetaTag::className(), 'targetAttribute' => ['meta_tag_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'content_id' => Yii::t('label', 'Content ID'),
            'meta_tag_id' => Yii::t('label', 'Meta Tag ID'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getContent()
    {
        return $this->hasOne(\common\models\SiteContent::className(), ['id' => 'content_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMetaTag()
    {
        return $this->hasOne(\common\models\SiteMetaTag::className(), ['id' => 'meta_tag_id']);
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\SiteContentMetaTagQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\SiteContentMetaTagQuery(get_called_class());
    }


}
