<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace yiix\models\base;

use Yii;

/**
 * This is the base-model class for table "site_plugin_event".
 *
 * @property integer $plugin_id
 * @property integer $event_id
 * @property integer $priority
 *
 * @property \common\models\SystemEvent $event
 * @property \common\models\SitePlugin $plugin
 * @property string $aliasModel
 */
abstract class SitePluginEvent extends \melkov\db\ActiveRecord 
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%site_plugin_event}}';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['plugin_id', 'event_id'], 'required'],
            [['plugin_id', 'event_id', 'priority'], 'integer'],
            [['event_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\SystemEvent::className(), 'targetAttribute' => ['event_id' => 'id']],
            [['plugin_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\SitePlugin::className(), 'targetAttribute' => ['plugin_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'plugin_id' => Yii::t('label', 'Plugin ID'),
            'event_id' => Yii::t('label', 'Event ID'),
            'priority' => Yii::t('label', 'Priority'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEvent()
    {
        return $this->hasOne(\common\models\SystemEvent::className(), ['id' => 'event_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPlugin()
    {
        return $this->hasOne(\common\models\SitePlugin::className(), ['id' => 'plugin_id']);
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\SitePluginEventQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\SitePluginEventQuery(get_called_class());
    }


}
