<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace yiix\models\base;

use Yii;

/**
 * This is the base-model class for table "site_module".
 *
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property integer $editor_type
 * @property integer $category_id
 * @property integer $disabled
 * @property integer $locked
 * @property string $icon
 * @property integer $created_on
 * @property integer $edited_on
 * @property string $guid
 * @property integer $enable_shared_params
 * @property string $code
 *
 * @property \common\models\Category $category
 * @property \common\models\SitePlugin[] $sitePlugins
 * @property \common\models\SiteSnippet[] $siteSnippets
 * @property string $aliasModel
 */
abstract class SiteModule extends \melkov\db\ActiveRecord 
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%site_module}}';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'description', 'icon', 'guid'], 'trim', 'skipOnEmpty' => true],
            [['name', 'created_on'], 'required'],
            [['editor_type', 'category_id', 'disabled', 'locked', 'created_on', 'edited_on', 'enable_shared_params'], 'integer'],
            [['code'], 'string'],
            [['name'], 'string', 'max' => 50],
            [['description', 'icon'], 'string', 'max' => 255],
            [['guid'], 'string', 'max' => 32],
            [['name'], 'unique'],
            [['category_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Category::className(), 'targetAttribute' => ['category_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('label', 'ID'),
            'name' => Yii::t('label', 'Name'),
            'description' => Yii::t('label', 'Description'),
            'editor_type' => Yii::t('label', 'Editor Type'),
            'category_id' => Yii::t('label', 'Category ID'),
            'disabled' => Yii::t('label', 'Disabled'),
            'locked' => Yii::t('label', 'Locked'),
            'icon' => Yii::t('label', 'Icon'),
            'created_on' => Yii::t('label', 'Created On'),
            'edited_on' => Yii::t('label', 'Edited On'),
            'guid' => Yii::t('label', 'Guid'),
            'enable_shared_params' => Yii::t('label', 'Enable Shared Params'),
            'code' => Yii::t('label', 'Code'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategory()
    {
        return $this->hasOne(\common\models\Category::className(), ['id' => 'category_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSitePlugins()
    {
        return $this->hasMany(\common\models\SitePlugin::className(), ['module_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSiteSnippets()
    {
        return $this->hasMany(\common\models\SiteSnippet::className(), ['module_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\SiteModuleQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\SiteModuleQuery(get_called_class());
    }


}
