<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace yiix\models\base;

use Yii;

/**
 * This is the base-model class for table "site_template_var_template".
 *
 * @property integer $template_id
 * @property integer $template_var_id
 * @property integer $rank
 *
 * @property \common\models\SiteTemplate $template
 * @property \common\models\SiteTemplateVar $templateVar
 * @property string $aliasModel
 */
abstract class SiteTemplateVarTemplate extends \melkov\db\ActiveRecord 
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%site_template_var_template}}';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['template_id', 'template_var_id'], 'required'],
            [['template_id', 'template_var_id', 'rank'], 'integer'],
            [['template_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\SiteTemplate::className(), 'targetAttribute' => ['template_id' => 'id']],
            [['template_var_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\SiteTemplateVar::className(), 'targetAttribute' => ['template_var_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'template_id' => Yii::t('label', 'Template ID'),
            'template_var_id' => Yii::t('label', 'Template Var ID'),
            'rank' => Yii::t('label', 'Rank'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTemplate()
    {
        return $this->hasOne(\common\models\SiteTemplate::className(), ['id' => 'template_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTemplateVar()
    {
        return $this->hasOne(\common\models\SiteTemplateVar::className(), ['id' => 'template_var_id']);
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\SiteTemplateVarTemplateQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\SiteTemplateVarTemplateQuery(get_called_class());
    }


}
