<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace yiix\models\base;

use Yii;

/**
 * This is the base-model class for table "site_template_var_content".
 *
 * @property integer $id
 * @property integer $content_id
 * @property integer $template_var_id
 * @property string $value
 *
 * @property \common\models\SiteContent $content
 * @property \common\models\SiteTemplateVar $templateVar
 * @property string $aliasModel
 */
abstract class SiteTemplateVarContent extends \melkov\db\ActiveRecord 
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%site_template_var_content}}';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['content_id', 'template_var_id'], 'required'],
            [['content_id', 'template_var_id'], 'integer'],
            [['value'], 'string'],
            [['content_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\SiteContent::className(), 'targetAttribute' => ['content_id' => 'id']],
            [['template_var_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\SiteTemplateVar::className(), 'targetAttribute' => ['template_var_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('label', 'ID'),
            'content_id' => Yii::t('label', 'Content ID'),
            'template_var_id' => Yii::t('label', 'Template Var ID'),
            'value' => Yii::t('label', 'Value'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getContent()
    {
        return $this->hasOne(\common\models\SiteContent::className(), ['id' => 'content_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTemplateVar()
    {
        return $this->hasOne(\common\models\SiteTemplateVar::className(), ['id' => 'template_var_id']);
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\SiteTemplateVarContentQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\SiteTemplateVarContentQuery(get_called_class());
    }


}
