<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace yiix\models\base;

use Yii;

/**
 * This is the base-model class for table "site_chunk".
 *
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property integer $editor_type
 * @property integer $category_id
 * @property string $content
 * @property integer $locked
 *
 * @property \common\models\Category $category
 * @property string $aliasModel
 */
abstract class SiteChunk extends \melkov\db\ActiveRecord 
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%site_chunk}}';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'description'], 'trim', 'skipOnEmpty' => true],
            [['name'], 'required'],
            [['editor_type', 'category_id', 'locked'], 'integer'],
            [['content'], 'string'],
            [['name'], 'string', 'max' => 50],
            [['description'], 'string', 'max' => 255],
            [['name'], 'unique'],
            [['category_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Category::className(), 'targetAttribute' => ['category_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('label', 'ID'),
            'name' => Yii::t('label', 'Name'),
            'description' => Yii::t('label', 'Description'),
            'editor_type' => Yii::t('label', 'Editor Type'),
            'category_id' => Yii::t('label', 'Category ID'),
            'content' => Yii::t('label', 'Content'),
            'locked' => Yii::t('label', 'Locked'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategory()
    {
        return $this->hasOne(\common\models\Category::className(), ['id' => 'category_id']);
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\SiteChunkQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\SiteChunkQuery(get_called_class());
    }


}
