<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace yiix\models\base;

use Yii;

/**
 * This is the base-model class for table "system_setting".
 *
 * @property string $name
 * @property string $value
 * @property string $aliasModel
 */
abstract class SystemSetting extends \melkov\db\ActiveRecord 
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%system_setting}}';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'trim', 'skipOnEmpty' => true],
            [['name'], 'required'],
            [['value'], 'string'],
            [['name'], 'string', 'max' => 50],
            [['name'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'name' => Yii::t('label', 'Name'),
            'value' => Yii::t('label', 'Value'),
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\SystemSettingQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\SystemSettingQuery(get_called_class());
    }


}
